import 'package:flutter/material.dart';
import 'demo1.dart';
import 'demo2.dart';
import 'demo3.dart';
import 'demo4.dart';
import 'demo5.dart';
import 'demo6.dart';
import 'demo7.dart';
import 'demo8.dart';
import 'demo9.dart';
import 'demo10.dart';
import 'demo11.dart';
import 'demo12.dart';
import 'demo13.dart';
import 'demo14.dart';
import 'demo15.dart';
import 'demo16.dart';
import 'demo17.dart';
import 'demo18.dart';
import 'demo19.dart';
import 'demo20.dart';

// void main() => runApp(Demo1App());
// void main() => runApp(Demo2App());
// void main() => runApp(Demo3App());
// void main() => runApp(Demo4App());
void main() => runApp(Demo5App());
// void main() => runApp(Demo6App());
// void main() => runApp(Demo7App());
// void main() => runApp(Demo8App());
// void main() => runApp(Demo9App());
// void main() => runApp(Demo10App());
// void main() => runApp(Demo11App());
// void main() => runApp(Demo12App());
// void main() => runApp(Demo13App());
// void main() => runApp(Demo14App());
// void main() => runApp(Demo15App());
// void main() => runApp(Demo16App());
// void main() => runApp(Demo17App());
// void main() => runApp(Demo18App());
// void main() => runApp(Demo19App());
// void main() => runApp(Demo20App());